---
language: rust
rust:
    - nightly
sudo: true

matrix:
  include:
    - os: windows
    - os: linux
      dist: bionic
cache:
  - apt
  - cargo

jobs:
  include:
    - os: windows
      - if: os = windows      
        script: 
          - cd agent
          - cargo build
          - cd ../controlcenter
          - cargo build
    - os: linux
      dist: bionic
      - if: os = linux
        script:
          - cd ./controlcenter
          - cargo build
