---
language: rust
rust:
    - nightly
sudo: true
cache:
  - apt
  - cargo

jobs:
  include:
    - name: Widnows
      - os: windows
      script: 
        - cd agent
        - cargo build
        - cd ../controlcenter
        - cargo build
    - name: Linux
        - os: linux
        dist: Focal
        script:
          - cd ../controlcenter
          - cargo build
