---
language: rust
rust:
    - nightly
sudo: true
cache:
  - apt
  - cargo
  - cmake
  - homebrew

matrix:
  include:
    - os: osx

#    
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - cmake

script:
  - rustup update
  - rustup target add x86_64-pc-windows-gnu
  - brew install mingw-w64
  - cd agent
  - cargo build --target x86_64-pc-windows-gnu
  - cd ../controlcenter
  - cargo build
