---
language: rust
rust:
    - nightly
sudo: true
cache:
  - apt
  - cargo
dist: bionic
addons:
  apt:
    addons:
      apt:
        update: true
        packages:
          - cmake
          - mingw-w64
#    
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - cmake

script:
  - rustup update
  - rustup target add x86_64-pc-windows-gnu
  - cd agent
  - cargo build --target x86_64-pc-windows-gnu
  - cd ../controlcenter
  - cargo build
