---
language: rust
rust:
    - nightly
sudo: true

matrix:
  include:
    - os: windows
        script: 
          - cd agent
          - cargo build
          - cd ../controlcenter
          - cargo build
    - os: linux
      dist: bionic
        script:
          - cd ./controlcenter
          - cargo build
cache:
  - apt
  - cargo

