---
language: rust
rust:
    - nightly
sudo: true
cache:
  - apt
  - cargo

jobs:
  include:
      - os: windows
      - os: linux
        dist: Focal
      - if: os = windows      
        script: 
          - cd agent
          - cargo build
          - cd ../controlcenter
          - cargo build
      - if: os = linux
        script:
          - cd ../controlcenter
          - cargo build
