---
language: rust
rust:
    - nightly
sudo: true
cache:
  - apt
  - cargo
  - cmake

matrix:
  include:
    - os: linux

    dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - rustup toolchain install stable-x86_64-pc-windows-gnu
  - rustup target add x86_64-pc-windows-gnu
  - cd agent
  - cargo build --target x86_64-pc-windows-gnu
  - cd ../controlcenter
  - cargo build
