---
language: rust
rust:
    - nightly

cache:
  - cargo

os:
  - windows
  - linux

jobs:
  include:
    - if: os = windows      
      script: 
        - cd agent
        - cargo build
        - cd ../controlcenter
        - cargo build
    - if: os = linux
      script:
        - cd ./controlcenter
        - cargo build
