---
language: rust
rust:
    - nightly

cache:
  - cargo

os:
  - windows
  -linux

jobs:
  include:
    - stage: windows
      os: windows      
      script: 
        - rustup update
        - cd agent
        - cargo build
        - cd ../controlcenter
        - cargo build
    - stage: linux
      os: linux
      script:
        - rustup update
        - cd ./controlcenter
        - cargo build
