---
language: rust
rust:
    - nightly
sudo: true
cache:
  - apt
  - cargo
  
matrix:
  include:
    - os: windows
    - os: linux
      dist: Focal

jobs:
  allow_failures:
    - os: linux
#    
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - cmake

script:
  - cd agent
  - cargo build 
  - cd ../controlcenter
  - cargo build
