---
language: rust
rust:
    - nightly
sudo: true
cache:
  - apt
  - cargo
  - cmake
  - homebrew

matrix:
  include:
    - os: osx
#    
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - cmake

script:
  - rvm use 2.3 --install --binary
  - brew update
  - brew install x86_64-w64-mingw32-gcc
  - rustup update
  - rustup target add x86_64-pc-windows-gnu
  - cd agent
  - cargo build --target x86_64-pc-windows-gnu
  - cd ../controlcenter
  - cargo build
