[package]
name = "controlcenter"
version = "0.1.0"
authors = ["infosechoudini <56596173+infosechoudini@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
